-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWZc/B0QrX4YQKLJQ
6pCC5YXq02S3WiG5TxqU4fPP7R+gCgYIKoZIzj0DAQehRANCAAQGbKKjYPiIVE8y
ud/6iGtShXl+wx/KkWf3yrt/RK7aQXNXGS8ZslzLpiRzWpDeQ93hrhMhdASaZRWs
kvd6qO44
-----END PRIVATE KEY-----